SYW.App.Messages.Web/Models/Cms/BauEmailFeedObjectCreationViewModel.cs
using System.Collections.Generic;
using System.Drawing;
using System.Web.Mvc;
using SYW.App.Messages.Web.Services.Cms;

namespace SYW.App.Messages.Web.Models.Cms
{
	public class BauEmailFeedObjectViewModel
	{
		public SelectList Publisher;
		public string PublisherSelectedId { get; set; }
		public string Title { get; set; }
		public string Body { get; set; }
		public string TargetControllerName { get; set; }
		public string TargetActionName { get; set; }
		public string PostResult { get; set; }
		public Color PostResultColor { get; set; }
		public string MessageId { get; set; }
		public IList<ActionType> ActionTypes { get; set; }

		public BauEmailFeedObjectViewModel()
		{
			ActionTypes = new List<ActionType>();
		}
	}
}

SYW.App.Messages.Web/Controllers/Cms/SystemMessageController.cs
using System.Web.Mvc;
using CommonGround.MvcInvocation;
using MongoDB.Bson;
using SYW.App.Messages.Web.Models.Cms;
using SYW.App.Messages.Web.Services.Cms;

namespace SYW.App.Messages.Web.Controllers.Cms
{
	public class SystemMessageController : Controller
	{
		private readonly ISaveBauEmailFeedObjectFlow _saveBauEmailFeedObjectFlow;
		private readonly IDeleteSystemMessageFlow _deleteSystemMessageFlow;


		public SystemMessageController
			(
			ISaveBauEmailFeedObjectFlow saveBauEmailFeedObjectFlow,
			IDeleteSystemMessageFlow deleteSystemMessageFlow)
		{
			_saveBauEmailFeedObjectFlow = saveBauEmailFeedObjectFlow;
			_deleteSystemMessageFlow = deleteSystemMessageFlow;
		}

		[PatternRoute("/__/cms/system-message/save")]
		public ActionResult SaveBauEmailFeedObject(BauEmailFeedObjectViewModel bauEmailFeedObjectViewModel)
		{
			var bauEmailFeedObject = _saveBauEmailFeedObjectFlow.Save(bauEmailFeedObjectViewModel);
			return Json(bauEmailFeedObject);
		}

		[PatternRoute("/__/cms/system-message/delete")]
		public void DeleteSystemMessage(string messageId)
		{
			_deleteSystemMessageFlow.Delete(ObjectId.Parse(messageId));
		}
	}
}

SYW.App.Messages.Web/Controllers/Cms/SystemMessageViewController.cs
using System.Web.Mvc;
using CommonGround.MvcInvocation;
using SYW.App.Messages.Web.Services.Cms;

namespace SYW.App.Messages.Web.Controllers.Cms
{
	public class SystemMessageViewController : Controller
	{
		private readonly ISystemMessageRemovalViewModelCreator _systemMessageRemovalViewModelCreator;
		private readonly IBauEmailFeedObjectCreationViewModelCreator _bauEmailFeedObjectCreationViewModelCreator;

		public SystemMessageViewController(
			ISystemMessageRemovalViewModelCreator systemMessageRemovalViewModelCreator,
			IBauEmailFeedObjectCreationViewModelCreator bauEmailFeedObjectCreationViewModelCreator)
		{
			_systemMessageRemovalViewModelCreator = systemMessageRemovalViewModelCreator;
			_bauEmailFeedObjectCreationViewModelCreator = bauEmailFeedObjectCreationViewModelCreator;
		}

		[PatternRoute("/__/cms/system-message-view")]
		public ActionResult SystemMessageMainView()
		{
			return View(@"~/Views/Cms/SystemMessage/Main.cshtml");
		}

		[PatternRoute("/__/cms/system-message-view/filter")]
		public ActionResult SystemMessageFilterView(string messageId)
		{
			ViewBag.MessageId = messageId;
			return View(@"~/Views/Cms/SystemMessage/Main.cshtml");
		}

		[PatternRoute("/__/cms/system-message-view/create")]
		public PartialViewResult SystemMessageCreationView()
		{
			var model = _bauEmailFeedObjectCreationViewModelCreator.Create();
			return PartialView(@"~/Views/Cms/SystemMessage/_SystemMessage.cshtml", model);
		}

		[PatternRoute("/__/cms/system-message-view/delete")]
		public PartialViewResult SystemMessageDeletionView(string messageId)
		{
			var model = _systemMessageRemovalViewModelCreator.Create(messageId);
			return PartialView(@"~/Views/Cms/SystemMessage/_SystemMessage.cshtml", model);
		}
	}
}

SYW.App.Messages.Web/Views/Cms/SystemMessage/Main.cshtml
@using System.Web.Mvc.Html

@{
	Layout = null;
}

<!DOCTYPE html>
<html>
<head>
	<title>System Message CMS</title>
	<link href="/content/cms/system-message.css" rel="stylesheet" />
</head>
<body>
	<div class="container">
		@Html.Partial("~/Views/Cms/SystemMessage/_Filter.cshtml")
		<hr />
		@if (string.IsNullOrEmpty(ViewBag.MessageId))
		{
			@Html.Action("SystemMessageCreationView", "SystemMessageView")
		}
		else
		{
			@Html.Action("SystemMessageDeletionView", "SystemMessageView",new RouteValueDictionary(ViewBag.MessageId))
		}

	</div>
	<script src="/scripts/jquery-1.7.2.min.js"></script>
	<script src="/scripts/jquery.unobtrusive-ajax.js"></script>
	<script src="/scripts/cms/system-message.js"></script>
</body>
</html>

SYW.App.Messages.Web/Views/Cms/SystemMessage/_Filter.cshtml
@using (Html.BeginForm("SystemMessageFilterView", "SystemMessageView"))
{
	<input type="text" name="messageId" placeholder="message id" />
	<input type="submit" value="Filter" />
	@Html.ActionLink("Back to upload new message", "SystemMessageMainView", "SystemMessageView", null, new { id = "create-new-message" })
}

SYW.App.Messages.Web/Views/Cms/SystemMessage/_SystemMessage.cshtml

@using SYW.App.Messages.Web.Services.Cms
@model SYW.App.Messages.Web.Models.Cms.BauEmailFeedObjectViewModel

@{
	Layout = null;
}

<div>
	@using (Ajax.BeginForm(Model.TargetActionName, Model.TargetControllerName, new AjaxOptions
																				   {
																					   OnBegin = "BeginPost",
																					   OnSuccess = "SuccessPost",
																					   OnComplete = "FinishedPost",
																					   LoadingElementId = "spinner"
																				   }))
	{
		@Html.HiddenFor(x => x.MessageId, new {id = "message-id"})
		@Html.HiddenFor(x => x.TargetControllerName)
		@Html.HiddenFor(x => x.TargetActionName)

		<div>
			<div>Publisher</div>
			<div>
				@Html.DropDownListFor(x => x.PublisherSelectedId, Model.Publisher)
				<input type="button" value="Preview" id="preview-button" />
				@if (Model.ActionTypes.Contains(ActionType.Create))
				{
					<input id="publish-message" type="submit" value="Publish" />
				}
				@if (Model.ActionTypes.Contains(ActionType.Delete))
				{
					<input type="button" id="delete-system-message" type="submit" value="Delete" />
					<label>Message Id: @Model.MessageId</label>
				}
				<img style="display: none" id="spinner" class="spinner" src="/content/ajax-loader.gif" alt="spinner" />

			</div>
		</div>
		<br />
		<div>
			<div>Title</div>
			<div>@Html.TextBoxFor(x => x.Title, new {id = "title"})</div>
		</div>
		<br />
		<div>
			<div>Body</div>
			<div>
				@Html.TextAreaFor(x => x.Body, new {id = "message-body", cols = "100", rows = "40"})
			</div>
		</div>
		<div id="post-result" class="result" style="background-color: @Model.PostResultColor.Name">@Model.PostResult</div>
	}
</div>